package mysql

import (
	"strings"
	"testing"
)

func TestIssue543CatalogColumnDeclarations(t *testing.T) {
	executor := ddlExecutorForTest(t)
	for _, test := range []struct{ view, declaration string }{
		{"tables", "TABLE_CATALOG|VARCHAR(64)|YES;TABLE_SCHEMA|VARCHAR(64)|YES;TABLE_NAME|VARCHAR(64)|YES;TABLE_TYPE|ENUM('BASE TABLE','VIEW','SYSTEM VIEW')|NO;ENGINE|VARCHAR(64)|YES;VERSION|INT|YES;ROW_FORMAT|ENUM('Fixed','Dynamic','Compressed','Redundant','Compact','Paged')|YES;TABLE_ROWS|BIGINT UNSIGNED|YES;AVG_ROW_LENGTH|BIGINT UNSIGNED|YES;DATA_LENGTH|BIGINT UNSIGNED|YES;MAX_DATA_LENGTH|BIGINT UNSIGNED|YES;INDEX_LENGTH|BIGINT UNSIGNED|YES;DATA_FREE|BIGINT UNSIGNED|YES;AUTO_INCREMENT|BIGINT UNSIGNED|YES;CREATE_TIME|TIMESTAMP|YES;UPDATE_TIME|DATETIME|YES;CHECK_TIME|DATETIME|YES;TABLE_COLLATION|VARCHAR(64)|YES;CHECKSUM|BIGINT|YES;CREATE_OPTIONS|VARCHAR(256)|YES;TABLE_COMMENT|TEXT|YES"},
		{"columns", "TABLE_CATALOG|VARCHAR(64)|YES;TABLE_SCHEMA|VARCHAR(64)|YES;TABLE_NAME|VARCHAR(64)|YES;COLUMN_NAME|VARCHAR(64)|YES;ORDINAL_POSITION|INT UNSIGNED|NO;COLUMN_DEFAULT|TEXT|YES;IS_NULLABLE|VARCHAR(3)|NO;DATA_TYPE|LONGTEXT|YES;CHARACTER_MAXIMUM_LENGTH|BIGINT|YES;CHARACTER_OCTET_LENGTH|BIGINT|YES;NUMERIC_PRECISION|BIGINT UNSIGNED|YES;NUMERIC_SCALE|BIGINT UNSIGNED|YES;DATETIME_PRECISION|INT UNSIGNED|YES;CHARACTER_SET_NAME|VARCHAR(64)|YES;COLLATION_NAME|VARCHAR(64)|YES;COLUMN_TYPE|MEDIUMTEXT|NO;COLUMN_KEY|ENUM('','PRI','UNI','MUL')|NO;EXTRA|VARCHAR(256)|YES;PRIVILEGES|VARCHAR(154)|YES;COLUMN_COMMENT|TEXT|NO;GENERATION_EXPRESSION|LONGTEXT|NO;SRS_ID|INT UNSIGNED|YES"},
	} {
		result, err := executeStatement(executor, "SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'information_schema' AND TABLE_NAME = '"+test.view+"' ORDER BY ORDINAL_POSITION")
		if err != nil {
			t.Fatal(err)
		}
		got := []string{}
		for _, row := range result.rows {
			got = append(got, strings.Join(row, "|"))
		}
		if strings.Join(got, ";") != test.declaration {
			t.Fatalf("%s declarations = %v; want %s", test.view, got, test.declaration)
		}
	}
}
